#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to

# 

CUR_DIR=`dirname $0`
source $CUR_DIR/util.sh

source $OPENSHIFT_REPO_DIR/etc/platformer_service_data.conf

if [ "$TELEMETRY_FEATURE_LIST" = "Manager" ]; then
	redis_reg_broker
else
	broker=redis_get_broker
fi
echo  TODO which file to put broker data in?
cd $OPENSHIFT_REPO_DIR/diy/telembaseinstall/bin
./telemetry-service start

# report manager url to service registry
# this environment variable should come from platformer when it spins up a service registry

