#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

#cd $OPENSHIFT_REPO_DIR/diy/telembaseinstall/bin
#./telemetry-service stop

killall java

source $OPENSHIFT_REPO_DIR/etc/platformer_service_data.conf
source `dirname $0`/util.sh
if [ "$TELEMETRY_FEATURE_LIST" = "Manager" ]; then
	redis_unreg_broker
fi

exit 0
